config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define a root route for when users log in
  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  root to: redirect('/users/sign_in') # Redirects non-logged-in users to the login page

  resources :projects do
    resources :project_comments, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/constants.rb
module Constants
  STATUSES = { created: 0, in_progress: 10, exchanged: 100, completed: 200, closed: 1000}.freeze
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_comments, inverse_of: :project, dependent: :destroy
  has_many :project_statuses, inverse_of: :project, dependent: :destroy
  belongs_to :user, inverse_of: :projects

  enum status: Constants::STATUSES

  validates :name, presence: true
  validates :status, presence: true

  accepts_nested_attributes_for :project_comments
  accepts_nested_attributes_for :project_statuses

  after_create :create_status_history
  after_update :update_status_history

  private
    def create_status_history
      ProjectStatus.create(user: user, project: self, status: 0)
    end

    def update_status_history
      return unless saved_change_to_status?

      ProjectStatus.create(user: user, project: self, status: status)
    end

end

app/models/project_comment.rb
class ProjectComment < ApplicationRecord
  belongs_to :user, inverse_of: :project_comments
  belongs_to :project, inverse_of: :project_comments

  validates :comment, presence: true
end

app/models/project_status.rb
class ProjectStatus < ApplicationRecord
  belongs_to :user, inverse_of: :project_statuses
  belongs_to :project, inverse_of: :project_statuses

  enum status: Constants::STATUSES

  validates :status, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, inverse_of: :user
  has_many :project_comments, inverse_of: :user
  has_many :project_statuses, inverse_of: :user

  enum role: { user: 0, buyer: 1, estate_agent: 2, solicitor: 3, surveyor: 4, admin: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/project_comments_controller.rb
class ProjectCommentsController < ApplicationController
  before_action :set_project

  def create
    @comment = @project.project_comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @project, notice: 'Comment was successfully added.'
    else
      redirect_to @project, alert: 'Comment could not be added.'
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def comment_params
    params.require(:project_comment).permit(:comment)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :status, 
    project_comments_attributes: [:id, :comment, :user_id], 
    project_statuses_attributes: [:id, :status, :user_id])
  end

  def set_status_updater
    return if params[:project][:project_statuses_attributes].nil?

    params[:project][:project_statuses_attributes].each do |status_attrs|
      status_attrs[:user_id] = current_user.id
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeyTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
    <header>
      <nav class="navbar">
        <div class="container">
          <%= link_to "Home", root_path, class: "navbar-brand" %>

          <div class="nav-links">
            <span>Welcome, <%= current_user.name %></span>
            <%= form_with url: destroy_user_session_path, method: :delete do %>
              <%= submit_tag "Log out", class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/projects/_comments.erb
<div class="comments-section-box">
  <h3>Comments</h3>

  <% if project.persisted? %>
    <div class="existing-comments">
      <table>
        <tr>
          <th>Comment</th>
          <th>Posted By</th>
          <th>Posted At</th>
        </tr>
        <% project.project_comments.each do |comment| %>
          <tr>
            <td><%= comment.comment %></td>
            <td><%= comment.user.name %></td>
            <td><%= comment.created_at %></td>
          </tr>
        <% end %>
      </table>
    </div>


    <%= form_with(model: [project, ProjectComment.new], local: true) do |f| %>
      <br />
      <div class="field">
        <%= f.text_area :comment %>
      </div>

      <div class="actions">
        <%= f.submit "Add" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="main-details">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :status %>
      <%= f.select :status, Constants::STATUSES.keys.map { |status| [status.to_s.humanize, status] }, prompt: "Select Status" %>
    </div>
</div>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<div class="existing-comments">
<table>
  <tr>
    <th>Name</td>
    <th>Status</td>
    <th>Created By</td>
    <th>Last Updated At</td>
  </tr>
  <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, project %></td>
      <td><%= project.status %></td>
      <td><%= project.user.name %></td>
      <td><%= project.updated_at %></td>
    </tr>
  <% end%>
</table>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<h1>Project Details</h1>

<div class="main-details">
  <p><strong>Name:</strong> <%= @project.name %></p>
  <p><strong>Current Status:</strong> <%= @project.status.humanize %></p>
</div>

<div class="project-additional-details">
  <div class="comments-section">
    <div class="existing-comments">
      <h2>Project Statuses</h2>
      <table>
        <tr>
          <th>Status</th>
          <th>User</th>
          <th>Date</th>
        </tr>
        <% @project.project_statuses.each do |status| %>
          <tr>
            <td><%= status.status %></td>
            <td><%= status.user.name %></td>
            <td><%= status.created_at %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

<div class="project-additional-details">
  <div class="comments-section">
    <%= render 'comments', project: @project %>
  </div>
</div>

<div class="actions">
  <%= link_to 'Edit Project', edit_project_path(@project), class: "btn btn-primary" %>
  <%= link_to 'Back to Projects', projects_path, class: "btn btn-secondary" %>
</div>

app/views/projects/update.html.erb
<h1>Edit Project</h1>

<%= render 'form', project: @project %>